server:
  port: 8081

spring:
  application:
    name: task-service
  cache:
    type: simple
    cache-names:
      - tasksById
      - tasksList

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
