spring:
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:local-project}
      pubsub:
        emulator-host: ${PUBSUB_EMULATOR_HOST:}

pubsub:
  subscription:
    notification: ${PUBSUB_SUBSCRIPTION_NOTIFICATION:notification-sub}
