{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "cloudops-platform.namespace" . }}
  labels:
    {{- include "cloudops-platform.labels" . | nindent 4 }}
{{- end }}
