{{- if .Values.jwt.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudops-jwt
  namespace: {{ include "cloudops-platform.namespace" . }}
  labels:
    {{- include "cloudops-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.jwt.existingSecretKey }}: {{ .Values.jwt.value | quote }}
{{- end }}
